#pragma once


//from glfw3.h

#define EDNA_MOUSE_BUTTON_1         0
#define EDNA_MOUSE_BUTTON_2         1
#define EDNA_MOUSE_BUTTON_3         2
#define EDNA_MOUSE_BUTTON_4         3
#define EDNA_MOUSE_BUTTON_5         4
#define EDNA_MOUSE_BUTTON_6         5
#define EDNA_MOUSE_BUTTON_7         6
#define EDNA_MOUSE_BUTTON_8         7
#define EDNA_MOUSE_BUTTON_LAST      EDNA_MOUSE_BUTTON_8
#define EDNA_MOUSE_BUTTON_LEFT      EDNA_MOUSE_BUTTON_1
#define EDNA_MOUSE_BUTTON_RIGHT     EDNA_MOUSE_BUTTON_2
#define EDNA_MOUSE_BUTTON_MIDDLE    EDNA_MOUSE_BUTTON_3